// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GuilhermeGabriel.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251021000328_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Consumo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AdicionalBandeira")
                        .HasColumnType("REAL");

                    b.Property<int>("Ano")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bandeira")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("M3Consumidos")
                        .HasColumnType("REAL");

                    b.Property<int>("Mes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PossuiEsgoto")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Tarifa")
                        .HasColumnType("REAL");

                    b.Property<double>("TaxaDeEsgoto")
                        .HasColumnType("REAL");

                    b.Property<double>("TotalGeral")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Consumos");
                });
#pragma warning restore 612, 618
        }
    }
}
